name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-13  # more stable than macos-latest (macOS 14)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Disable Code Signing
        run: |
          echo 'CODE_SIGN_IDENTITY=' >> ios/disable-signing.xcconfig
          echo 'CODE_SIGNING_REQUIRED=NO' >> ios/disable-signing.xcconfig
          echo 'CODE_SIGN_ENTITLEMENTS=' >> ios/disable-signing.xcconfig
          echo 'CODE_SIGNING_ALLOWED=NO' >> ios/disable-signing.xcconfig

      - name: Archive the app
        run: |
          xcodebuild \
            -workspace ios/kittenstore.xcworkspace \
            -scheme kittenstore \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/kittenstore.xcarchive \
            -xcconfig ios/disable-signing.xcconfig \
            archive | xcpretty

      - name: Create export options plist
        run: |
          cat > exportOptions.plist <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOL

      - name: Export IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath build/kittenstore.xcarchive \
            -exportPath build/export \
            -exportOptionsPlist exportOptions.plist | xcpretty

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/export/*.ipa
